# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "61b36a57ba82c920e1c9ca04d6595cad"
name = "development"
handle = "development-43"
application_url = "https://app.iwantthat.io/version-test/authorize"
embedded = false

[build]
dev_store_url = "oldetownehardware.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_all_orders,read_billing,read_checkouts,read_customers,read_discounts,read_discounts_allocator_functions,read_inventory,read_locations,read_metaobject_definitions,read_metaobjects,read_orders,read_price_rules,read_product_listings,read_products,read_themes,write_billing,write_checkouts,write_customers,write_discounts,write_discounts_allocator_functions,write_metaobject_definitions,write_metaobjects,write_products,write_themes"

[auth]
redirect_urls = [ "https://app.iwantthat.io/version-test/oauth2callback" ]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  uri = "https://app.iwantthat.io/version-test/api/1.1/wf/gdpr-customer-data-redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "https://app.iwantthat.io/version-test/api/1.1/wf/gdpr-customer-data-request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "https://app.iwantthat.io/version-test/api/1.1/wf/gdpr-shop-data-redact"
  compliance_topics = [ "shop/redact" ]

[pos]
embedded = false
