api_version = "2024-10"

# Existing theme extension (App Block)
[[extensions]]
name = "I Want That!"
description = "Wanna Make a Deal"
handle = "i-want-that-app"
type = "theme"

[extensions.capabilities]
  api_access = true

