api_version = "2024-10"

# Existing theme extension (App Block)
[[extensions]]
name = "iwt-modal-button"
description = "Wanna Make a Deal"
handle = "iwt-modal-button"
type = "theme"

[extensions.capabilities]
  api_access = true

