api_version = "2024-10"

# Existing theme extension (App Block)
[[extensions]]
name = "iwt-modal-button"
description = "Make an Offer Button"
handle = "iwt-modal-button"
type = "theme"

[extensions.capabilities]
  api_access = true

